version: '3'

services:
  app:
    build: docker
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1g
    #     reservations:
    #       memory: 300M
    ports:
        - '3000:3000'
    volumes:
        - ./app:/home/nodejs/app
    tty: true

  redis:
    image: redis:latest
    ports:
        - '6379:6379'

volumes:
  app:
    driver: local